import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('ホームから試合を開始して公開／GM視点とリプレイを表示できる', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'AI人狼' })).toBeVisible();
  await expect(page.getByRole('button', { name: '♫ BGM ON' })).toBeVisible();
  await expect(page.getByLabel('BGM音量')).toBeVisible();
  await expect(page.getByLabel('BGM音量')).toHaveValue('70');
  await page.getByLabel('BGM音量').fill('85');
  await page.getByLabel(/SEED/).fill('fixture-0');
  await page.getByText('最速').click();
  await page.getByRole('button', { name: /AI人狼を開始/ }).click();
  await expect(page).toHaveURL(/\/match\//);
  await expect(page.locator('.cinematic-overlay')).toContainText('第0夜');
  await expect(page.locator('.cinematic-overlay')).toContainText('1日目', { timeout: 10_000 });
  await expect(page.getByRole('heading', { name: '名取 澪' })).toBeVisible();
  await page.getByRole('button', { name: '？ ルール' }).click();
  await expect(page.getByRole('dialog', { name: '観戦ガイド' })).toBeVisible();
  await expect(page.getByRole('button', { name: '観戦ガイドを閉じる' })).toBeFocused();
  await expect(page.getByRole('heading', { name: '9人の配役' })).toBeVisible();
  await expect(page.getByText('狂人 ×1')).toBeVisible();
  await expect(page.getByText('公開視点', { exact: true }).last()).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog', { name: '観戦ガイド' })).toBeHidden();
  await expect(page.getByText(/生存 \d\/9/)).toBeVisible();
  await expect(page.getByAltText('名取 澪の立ち絵')).toBeVisible();
  await expect(page.getByText('世話焼きの心配性')).toBeVisible();
  await expect(page.locator('audio[data-bgm-player="true"]')).toHaveAttribute('src', '/assets/bgm_village.ogg');
  await expect(page.getByRole('button', { name: /VOICE ON/ })).toBeVisible();
  await expect(page.getByRole('button', { name: '◆ SE ON' })).toBeVisible();
  await expect(page.getByLabel('SE音量')).toHaveValue('80');
  await page.getByLabel('SE音量').fill('35');
  await expect.poll(() => page.evaluate(() => window.localStorage.getItem('werewolf-sfx-volume'))).toBe('0.35');
  await page.getByRole('button', { name: '◆ SE ON' }).click();
  await expect(page.getByRole('button', { name: '◆ SE OFF' })).toBeVisible();
  await page.getByRole('button', { name: '◆ SE OFF' }).click();
  await expect(page.getByLabel('VOICE音量')).toBeVisible();
  await expect(page.getByLabel('VOICE音量')).toHaveValue('90');
  await page.getByLabel('VOICE音量').fill('75');
  await page.getByRole('button', { name: /VOICE ON/ }).click();
  await expect(page.getByRole('button', { name: /VOICE OFF/ })).toBeVisible();
  await page.getByRole('button', { name: 'GM視点' }).click();
  await expect(page.getByText(/村人|人狼|占い師|霊媒師|狩人|狂人/).first()).toBeVisible();
  await expect(page.getByText('GAME SET')).toBeVisible({ timeout: 30_000 });
  await expect(page.getByRole('heading', { name: '全員の正体と結末' })).toBeVisible();
  await expect(page.getByRole('heading', { name: '役職主張' })).toBeVisible();
  await expect(page.getByText('本人の公開主張です。真偽を示しません。')).toBeVisible();
  const claimBoardBox = await page.locator('.claim-board').boundingBox();
  const timelinePanelBox = await page.locator('.timeline-panel').boundingBox();
  expect(claimBoardBox?.x).toBeGreaterThanOrEqual(timelinePanelBox?.x ?? 0);
  expect((claimBoardBox?.x ?? 0) + (claimBoardBox?.width ?? 0)).toBeLessThanOrEqual((timelinePanelBox?.x ?? 0) + (timelinePanelBox?.width ?? 0));
  await expect(page.getByRole('region', { name: '村人陣営の配役' })).toBeVisible();
  await expect(page.getByRole('region', { name: '人狼陣営の配役' })).toBeVisible();
  await expect(page.locator('.epilogue-team li')).toHaveCount(9);
  await expect(page.locator('.epilogue-team li').filter({ hasText: '狂人（判定は人間）' })).toHaveCount(1);
  await expect(page.locator('.epilogue-fate')).toHaveCount(9);
  await expect(page.locator('.timeline-event.dawn').filter({ hasText: '1日目' })).toHaveCount(0);
  await expect(page.locator('.voter-chips span').first()).toBeVisible();
  await expect(page.locator('.timeline-day').first()).toBeVisible();
  await page.getByRole('button', { name: '公開視点' }).click();
  await expect(page.getByText('REVEALED SECRET').first()).toBeVisible();
  await expect(page.locator('.card-vote').first()).toBeVisible();
  await expect(page.getByRole('link', { name: 'リプレイを見る →' })).toBeVisible();
  await page.reload();
  await expect(page.getByText('GAME SET')).toBeVisible();
  await expect(page.getByLabel('SE音量')).toHaveValue('35');
  await expect(page.locator('.cinematic-overlay')).toHaveCount(0);
  const replayUrl = page.url().replace('/match/', '/replay/');
  await page.goto(replayUrl);
  await expect(page.getByLabel('リプレイ位置')).toBeVisible();
  await page.getByLabel('リプレイ位置').fill('0');
  await expect(page.getByRole('heading', { name: '全員の正体と結末' })).toHaveCount(0);
  await expect(page.locator('.timeline-event.dawn').filter({ hasText: '1日目' })).toHaveCount(0);
  const voteRevealSeq = await page.evaluate(async () => {
    const matchId = window.location.pathname.split('/').at(-1);
    const response = await fetch(`/api/match/${matchId}?view=public`);
    const data = await response.json() as { events: Array<{ seq: number; type: string }> };
    return data.events.find((event) => event.type === 'vote_reveal')?.seq ?? 0;
  });
  await page.getByLabel('リプレイ位置').fill(String(voteRevealSeq));
  await expect(page.locator('.cinematic-overlay')).toContainText('開票', { timeout: 15_000 });
});

test('Spaceキーでゲームと発言音声を一時停止・再開し、中断できる', async ({ page }) => {
  const voiceAudio = await readFile('public/assets/bgm_village.ogg');
  await page.route('**/api/voicevox', async (route) => {
    if (route.request().method() === 'GET') {
      await route.fulfill({ json: { available: true } });
      return;
    }
    await route.fulfill({ status: 200, contentType: 'audio/ogg', body: voiceAudio });
  });
  await page.goto('/');
  await page.getByRole('button', { name: /AI人狼を開始/ }).click();
  await expect(page).toHaveURL(/\/match\//);
  await expect(page.getByRole('heading', { name: '名取 澪' })).toBeVisible();
  await expect(page.locator('.cinematic-overlay')).toContainText('第0夜');
  await expect(page.locator('.agent-card.speaking')).toHaveCount(0);
  await expect(page.locator('.cinematic-overlay')).toContainText('1日目', { timeout: 15_000 });
  await expect(page.locator('.agent-card.speaking')).toHaveCount(0);
  await expect(page.locator('.cinematic-overlay')).toHaveCount(0, { timeout: 10_000 });
  await expect(page.locator('.viewer-shell')).toHaveClass(/day/);
  await expect(page.locator('.agent-card.speaking')).toHaveCount(1, { timeout: 30_000 });
  const speakingName = await page.locator('.agent-card.speaking h2').textContent();
  const speakingText = await page.locator('.agent-card.speaking blockquote').textContent();
  await expect(page.getByRole('region', { name: '注目中の発言' })).toBeVisible();
  await expect(page.locator('.speaker-stage h2')).toContainText(speakingName ?? '');
  await expect(page.locator('.speaker-stage blockquote')).toContainText(speakingText ?? '');
  const speakerStageBox = await page.locator('.speaker-stage').boundingBox();
  const controlDockBox = await page.locator('.control-dock').boundingBox();
  const lastAgentBox = await page.locator('.agent-card').last().boundingBox();
  await expect(page.locator('.agent-card')).toHaveCount(9);
  expect(speakerStageBox?.height).toBeLessThanOrEqual(134);
  expect((speakerStageBox?.y ?? 0) + (speakerStageBox?.height ?? 0)).toBeLessThanOrEqual(controlDockBox?.y ?? 0);
  expect((lastAgentBox?.y ?? 0) + (lastAgentBox?.height ?? 0)).toBeLessThanOrEqual(controlDockBox?.y ?? 0);
  await expect(page.locator('.vote-panel')).toHaveCount(0);
  await page.keyboard.press('Space');
  await expect(page.locator('.round-status em')).toHaveText('PAUSED');
  await expect(page.locator('.agent-card.speaking')).toHaveCount(0);
  await expect(page.locator('.speaker-stage')).toHaveClass(/paused/);
  await expect(page.locator('.speaker-stage')).toContainText('PAUSED');
  const pausedEventCount = await page.locator('.timeline-event').count();
  await page.waitForTimeout(1_200);
  await expect(page.locator('.timeline-event')).toHaveCount(pausedEventCount);
  await page.keyboard.press('Space');
  await expect(page.locator('.round-status em')).toHaveText('LIVE');
  await expect(page.locator('.agent-card.speaking')).toHaveCount(1);
  await page.getByRole('button', { name: '中断' }).click();
  await expect(page.getByText('ABORTED')).toBeVisible();
});
